"""
Validation Scorecard: held-out comparison of downscaling vs baselines.
Generates deterministic synthetic truth values with known terrain effects.
"""
import math
import random
from typing import List

import numpy as np

RNG = random.Random(99)


def generate_truth(panchayat: dict, block_rain: float, block_tmax: float) -> dict:
    """
    Synthetic "ground truth" for validation generated by the same physics
    but with extra noise, simulating real observations.
    """
    elev_effect_rain = (panchayat["elevation_m"] - 400) / 1000.0 * block_rain * 0.8
    ndvi_effect_rain = panchayat["ndvi"] * 0.15 * block_rain
    noise_rain = RNG.gauss(0, max(1.0, block_rain * 0.1))
    true_rain = max(0.0, block_rain + elev_effect_rain + ndvi_effect_rain + noise_rain)

    lapse_effect = (panchayat["elevation_m"] - 400) * (-0.006)
    water_effect = max(0, 3.0 - panchayat["dist_water_km"]) * (-0.15)
    noise_tmax = RNG.gauss(0, 0.4)
    true_tmax = block_tmax + lapse_effect + water_effect + noise_tmax

    return {
        "true_rain_mm": round(max(0.0, true_rain), 2),
        "true_tmax_c": round(true_tmax, 2),
    }


def compute_metrics(errors: List[float]) -> dict:
    if not errors:
        return {"mae": None, "rmse": None}
    arr = np.array(errors)
    return {
        "mae": round(float(np.mean(np.abs(arr))), 3),
        "rmse": round(float(np.sqrt(np.mean(arr ** 2))), 3),
    }


def build_validation_scorecard(panchayats: List[dict], all_results: List[dict]) -> dict:
    """
    Build held-out validation scorecard grouped by terrain type.
    Compares: WeatherTwin vs Block-Copy vs IDW Interpolation.
    """
    terrain_groups = {
        "Hills (Kundam)": "hilly_forest",
        "Plains (Panagar)": "flat_plains",
        "Riverine (Bargi)": "riverine_reservoir",
    }

    scorecard = {}
    for label, terrain_key in terrain_groups.items():
        idxs = [i for i, p in enumerate(panchayats) if p.get("terrain") == terrain_key]

        twin_rain_err, twin_tmax_err = [], []
        copy_rain_err, copy_tmax_err = [], []
        idw_rain_err, idw_tmax_err = [], []

        for i in idxs:
            r = all_results[i]
            truth = r.get("truth", {})
            tr = truth.get("true_rain_mm")
            tt = truth.get("true_tmax_c")

            if tr is None or tt is None:
                continue

            twin_rain_err.append(r["rain_mm"] - tr)
            twin_tmax_err.append(r["tmax_c"] - tt)
            copy_rain_err.append(r["baselines"]["block_copy_rain_mm"] - tr)
            copy_tmax_err.append(r["baselines"]["block_copy_tmax_c"] - tt)
            idw_rain_err.append(r["baselines"]["idw_rain_mm"] - tr)
            idw_tmax_err.append(r["baselines"]["idw_tmax_c"] - tt)

        scorecard[label] = {
            "n_panchayats": len(idxs),
            "rain": {
                "WeatherTwin": compute_metrics(twin_rain_err),
                "Block-Copy": compute_metrics(copy_rain_err),
                "IDW Interpolation": compute_metrics(idw_rain_err),
            },
            "tmax": {
                "WeatherTwin": compute_metrics(twin_tmax_err),
                "Block-Copy": compute_metrics(copy_tmax_err),
                "IDW Interpolation": compute_metrics(idw_tmax_err),
            },
        }

    return scorecard
